import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { ButtonScrollTop } from '@/components/ButtoScrollToTop/ButtonScrollTop'

const roboto = Roboto({weight:'400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portal da Transparência',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
        {/* <ButtonScrollTop /> */}
      </body>
    </html>
  )
}
